# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/JI Files/VE270_Vivado/Lab6_Helina/Lab6/Lab6.cache/wt} [current_project]
set_property parent.project_path {E:/JI Files/VE270_Vivado/Lab6_Helina/Lab6/Lab6.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {e:/JI Files/VE270_Vivado/Lab6_Helina/Lab6/Lab6.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {E:/JI Files/VE270_Vivado/Lab6_Helina/Lab6/Lab6.srcs/sources_1/new/Key_Scanner.v}
  {E:/JI Files/VE270_Vivado/Lab6_Helina/Lab6/Lab6.srcs/sources_1/new/Register.v}
  {E:/JI Files/VE270_Vivado/Lab6_Helina/Lab6/Lab6.srcs/sources_1/new/SSD.v}
  {E:/JI Files/VE270_Vivado/Lab6_Helina/Lab6/Lab6.srcs/sources_1/new/LAB6.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/JI Files/VE270_Vivado/Lab6_Helina/Lab6/Lab6.srcs/constrs_1/new/Constraint.xdc}}
set_property used_in_implementation false [get_files {{E:/JI Files/VE270_Vivado/Lab6_Helina/Lab6/Lab6.srcs/constrs_1/new/Constraint.xdc}}]


synth_design -top LAB6 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef LAB6.dcp

catch { report_utilization -file LAB6_utilization_synth.rpt -pb LAB6_utilization_synth.pb }
