# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/JI Files/VE270_Vivado/Lab_5/Lab_5.cache/wt} [current_project]
set_property parent.project_path {E:/JI Files/VE270_Vivado/Lab_5/Lab_5.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {e:/JI Files/VE270_Vivado/Lab_5/Lab_5.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {E:/JI Files/VE270_Vivado/Lab_5/Lab_5.srcs/sources_1/new/CD1.v}
  {E:/JI Files/VE270_Vivado/Lab_5/Lab_5.srcs/sources_1/new/CD2.v}
  {E:/JI Files/VE270_Vivado/Lab_5/Lab_5.srcs/sources_1/new/RC.v}
  {E:/JI Files/VE270_Vivado/Lab_5/Lab_5.srcs/sources_1/new/SSD.v}
  {E:/JI Files/VE270_Vivado/Lab_5/Lab_5.srcs/sources_1/new/Timer.v}
  {E:/JI Files/VE270_Vivado/Lab_5/Lab_5.srcs/sources_1/new/Lab_5.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/JI Files/VE270_Vivado/Lab_5/Lab_5.srcs/constrs_1/new/Constraints.xdc}}
set_property used_in_implementation false [get_files {{E:/JI Files/VE270_Vivado/Lab_5/Lab_5.srcs/constrs_1/new/Constraints.xdc}}]


synth_design -top Lab_5 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Lab_5.dcp

catch { report_utilization -file Lab_5_utilization_synth.rpt -pb Lab_5_utilization_synth.pb }
