set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN U18 [get_ports reset]


set_property PACKAGE_PIN W7 [get_ports {SSD[6]}]
set_property PACKAGE_PIN W6 [get_ports {SSD[5]}]
set_property PACKAGE_PIN U8 [get_ports {SSD[4]}]
set_property PACKAGE_PIN V8 [get_ports {SSD[3]}]
set_property PACKAGE_PIN U5 [get_ports {SSD[2]}]
set_property PACKAGE_PIN V5 [get_ports {SSD[1]}]
set_property PACKAGE_PIN U7 [get_ports {SSD[0]}]
set_property PACKAGE_PIN W5 [get_ports clk_100M]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100M]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]


set_property PACKAGE_PIN U2 [get_ports {AN[3]}]
set_property PACKAGE_PIN W4 [get_ports {AN[2]}]
set_property PACKAGE_PIN V4 [get_ports {AN[1]}]
set_property PACKAGE_PIN U4 [get_ports {AN[0]}]
